sudo: required
services:
  - docker

before_install:
  - docker build -t phuctranlv/learn-docker-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true phuctranlv/learn-docker-complex-test npm test

after_success:
  - docker build -t phuctranlv/learn-docker-complex-client -f ./client/Dockerfile ./client
  - docker build -t phuctranlv/learn-docker-complex-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t phuctranlv/learn-docker-complex-server -f ./server/Dockerfile ./server
  - docker build -t phuctranlv/learn-docker-complex-worker -f ./worker/Dockerfile ./worker
  - echo "$DOCKER_pass" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push phuctranlv/learn-docker-complex-client
  - docker push phuctranlv/learn-docker-complex-nginx
  - docker push phuctranlv/learn-docker-complex-server
  - docker push phuctranlv/learn-docker-complex-worker